import "./globals.css";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";

import { SourceProvider } from "@/providers/SourceProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
    return (
        <html lang="en" className={inter.variable}>
            <body className={clsx(inter.className, "antialiased")}>
                <SourceProvider>{children}</SourceProvider>
            </body>
        </html>
    );
}
