import "./globals.css";
import clsx from "clsx";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";

import { QueryClientProvider } from "@/providers/QueryClientProvider";
import { SourcesProvider } from "@/providers/SourcesProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const fontSans = Geist({
    subsets: ["latin"],
    variable: "--font-sans",
});

const fontMono = Geist_Mono({
    subsets: ["latin"],
    variable: "--font-mono",
});

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
    return (
        <html lang="en" className={clsx(fontSans.variable, fontMono.variable)}>
            <body className={clsx(fontSans.className, "antialiased")}>
                <QueryClientProvider>
                    <SourcesProvider>{children}</SourcesProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
